In [6]:
import numpy as np

In [7]:
A=[2.43334,2.43334,4.99926]

In [8]:
B=np.array([[2.43334,7.30000,4.99926],
[7.30000,2.43334,4.99926],
[-2.43334,2.43334,4.99926],
[2.43334,-2.43334,4.99926]])

In [12]:
a1=0.5*(A+B[0])
a2=0.5*(A+B[1])
a3=0.5*(A+B[2])
a4=0.5*(A+B[3])
print(a1)
print(a2)
print(a3)
print(a4)

[2.43334 4.86667 4.99926]
[4.86667 2.43334 4.99926]
[0.      2.43334 4.99926]
[2.43334 0.      4.99926]
